import { BANNED } from "@/lib/draft-prompts";
import type { DraftArticle } from "@/lib/draft-types";

/* The sub-editor's desk: reject-don't-repair checks run on every draft before
   it reaches the visitor. Deterministic on purpose — the prompt asks the model
   to stay grounded, these rules are what actually enforce it. */

const NUM_WORDS: Record<string, string> = {
  one: "1", two: "2", three: "3", four: "4", five: "5", six: "6", seven: "7", eight: "8",
  nine: "9", ten: "10", eleven: "11", twelve: "12", thirteen: "13", fourteen: "14",
  fifteen: "15", sixteen: "16", seventeen: "17", eighteen: "18", nineteen: "19",
  twenty: "20", thirty: "30", forty: "40", fifty: "50", sixty: "60", seventy: "70",
  eighty: "80", ninety: "90", hundred: "100", thousand: "1000",
};

/* Only quantities attached to a unit count as factual claims. Bare number words
   ("one of the first", "no one") are prose, not data, and must not trip the check. */
const UNITS =
  "years?|yrs?|months?|weeks?|days?|decades?|cities|towns|states?|countries|" +
  "clients?|customers?|patients?|students?|employees?|staff|people|teams?|members?|" +
  "brands?|stores?|outlets?|branches|locations?|centres?|centers?|clinics?|" +
  "products?|orders?|units?|projects?|campaigns?|awards?|publications?|placements?|" +
  "lakh|lakhs|crore|crores|million|billion|per\\s?cent|percent|%|x|times";

const normalise = (n: string) => n.replace(/[,\s]/g, "").replace(/\.0+$/, "");

/** Every number the submission actually contains, digits and spelled-out alike. */
function submittedNumbers(submission: string): Set<string> {
  const out = new Set<string>();
  const low = submission.toLowerCase();
  for (const m of low.matchAll(/\d[\d,]*(?:\.\d+)?/g)) out.add(normalise(m[0]));
  for (const [word, digit] of Object.entries(NUM_WORDS)) {
    if (new RegExp(`\\b${word}\\b`).test(low)) out.add(digit);
  }
  return out;
}

/**
 * Returns the first quantified claim in the article that the submission does not
 * support, or null when every figure is traceable. This is what stops ledes like
 * "After five years building a manufacturing venture" when no such span was given.
 */
export function ungroundedQuantity(article: DraftArticle, submission: string): string | null {
  const prose = [
    article.headline,
    article.dek,
    ...(article.body_paragraphs || []),
    article.quote?.text || "",
    article.pull_quote || "",
  ]
    .join(" ")
    .toLowerCase();

  const allowed = submittedNumbers(submission);
  const numberWord = Object.keys(NUM_WORDS).join("|");
  const claim = new RegExp(`\\b(\\d[\\d,]*(?:\\.\\d+)?|${numberWord})\\s+(?:${UNITS})\\b`, "g");

  for (const m of prose.matchAll(claim)) {
    const raw = m[1];
    const value = /^\d/.test(raw) ? normalise(raw) : NUM_WORDS[raw];
    if (!allowed.has(value)) return m[0].trim();
  }
  return null;
}

/** Returns a failure code, or null when the draft is clean. */
export function qaFail(a: DraftArticle | null, submission: string): string | null {
  if (!a || typeof a !== "object") return "schema";
  const paras = Array.isArray(a.body_paragraphs) ? a.body_paragraphs : null;
  if (!paras || paras.length < 2 || paras.length > 5) return "paragraphs";
  if (!a.headline || !a.dek || !a.quote || !a.quote.text) return "schema";
  const wc = Number(a.word_count) || paras.join(" ").split(/\s+/).filter(Boolean).length;
  if (wc < 200 || wc > 470) return `word_count(${wc})`;
  const fields = [a.headline, a.dek, ...paras, a.quote.text, a.pull_quote || ""].join(" ");
  if (/!/.test(a.headline) || paras.some((p) => /!/.test(p))) return "exclamation";
  if (a.headline.split(/\s+/).length > 13) return "headline_len";
  if (/:\s*The\b/i.test(a.headline)) return "headline_colon";
  if (a.quote.text.split(/\s+/).length > 40) return "quote_len";
  if (/\b(StoryBizz|as an AI|generated by)\b/i.test(fields)) return "meta_leak";
  const low = fields.toLowerCase();
  for (const w of BANNED) {
    if (w.includes("*")) {
      if (new RegExp(w.replace("*", "\\w+")).test(low)) return `banned:${w}`;
    } else if (low.includes(w)) {
      return `banned:${w}`;
    }
  }
  const invented = ungroundedQuantity(a, submission);
  if (invented) return `ungrounded:${invented}`;
  return null;
}

/* Obvious junk, caught before we spend a model call on it. Deliberately
   conservative: it only fires on degenerate text, because a terse-but-real
   story must reach the desk and come back as a short article. The subtler
   "no reportable content" judgement is left to the gatekeeper. */
export function looksUnusable(story: string): boolean {
  const text = story.trim();
  if (!text) return true;
  if (/\blorem ipsum\b|\bdolor sit amet\b/i.test(text)) return true;

  /* a wall built from two or three keys */
  const letters = text.replace(/[^a-z]/gi, "").toLowerCase();
  if (letters.length >= 20 && new Set(letters).size <= 3) return true;

  const words = text.toLowerCase().split(/\s+/).filter(Boolean);
  /* 60+ characters and barely a word break is a keysmash, not a sentence */
  if (words.length <= 2 && text.length >= 60) return true;
  /* the same one or two words over and over */
  if (words.length >= 8 && new Set(words).size <= 2) return true;

  /* mostly vowel-less tokens — "asdf jkl qwrt" and friends */
  const alpha = words.map((w) => w.replace(/[^a-z]/gi, "")).filter((w) => w.length > 1);
  if (alpha.length >= 6) {
    const vowelless = alpha.filter((w) => !/[aeiouy]/i.test(w)).length;
    if (vowelless / alpha.length > 0.7) return true;
  }
  return false;
}
